# Generated by Django 3.2.25 on 2024-08-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=2560, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2560)),
                ('author', models.CharField(max_length=2560)),
                ('year', models.IntegerField()),
                ('publisher', models.CharField(max_length=2560)),
                ('image_s', models.URLField()),
                ('image_m', models.URLField()),
                ('image_l', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
    ]
