# Generated by Django 3.2.25 on 2024-08-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('isbn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.book')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.usermanager')),
            ],
            options={
                'unique_together': {('user_id', 'isbn')},
            },
        ),
    ]
