# Generated by Django 4.1.7 on 2024-08-13 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_rating"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together=set(),
        ),
    ]
